version: '3.1'

services:
  api:
    build: .
    restart: unless-stopped
    command: npm start
    ports:
      - 3000:3000
      - 65080:65080
    volumes:
      - .:/usr/app
      - /usr/app/node_modules/
      - ./websocket/certs/cert.key:/usr/app/cert.key
      - ./websocket/certs/cert.crt:/usr/app/cert.crt
  # database:
  #   container_name: postgres-teste
  #   image: postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_PASSWORD: 1212
  #     POSTGRES_USER: postesolar
  #   ports:
  #     - 5435:5432
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
# volumes:
#   db-data:
