version: "3.1"

services:
  api:
    container_name: api
    build: .
    restart: unless-stopped
    command: npm start
    ports:
      - 3000:3000
      - 65080:65080
    volumes:
      - .:/usr/app
      - /usr/app/node_modules/
      - /home/postesolar/conf/web:/usr/app/conf
    networks:
      - api
    depends_on:
      - "database"
      - "emqx"
      - "mongo"
      - "redis"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
  database:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 6TmMrPc_h2ST3UpxQ
      POSTGRES_USER: postesolar
    ports:
      - 5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  emqx:
    container_name: emqx
    restart: unless-stopped
    image: emqx/emqx
    environment:
      - "EMQX_LISTENER__WS__EXTERNAL=9083"
      - "EMQX_LISTENER__WSS__EXTERNAL=9084"
      - "EMQX_LISTENER__TCP__EXTERNAL=9883"
      - "EMQX_LISTENER__SSL__EXTERNAL=9884"
      - "EMQX_LOADED_PLUGINS=emqx_auth_pgsql,emqx_recon,emqx_management,emqx_dashboard"
      - "EMQX_AUTH__PGSQL__SERVER=vps.fernandoneto.com.br:5433"
      - "EMQX_AUTH__PGSQL__USERNAME=postesolar"
      - "EMQX_AUTH__PGSQL__PASSWORD=6TmMrPc_h2ST3UpxQ"
      - "EMQX_AUTH__PGSQL__DATABASE=postesolar"
      - "EMQX_AUTH__PGSQL__PASSWORD_HASH=plain"
      - "EMQX_ALLOW_ANONYMOUS=false"
    ports:
      - 18083:18083
      - 9083:9083
      - 9084:9084
      - 9883:9883
      - 9884:9884
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-etc:/opt/emqx/etc
      - emqx-log:/opt/emqx/log
    networks:
      - api
    depends_on:
      - "database"
      - "mongo"
      - "redis"
  mongo:
    container_name: mongodb
    image: mongo
    command: [--auth]
    restart: unless-stopped
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: postesolar
    #   MONGO_INITDB_ROOT_PASSWORD: 6TmMrPc_h2ST3UpxQ
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    networks:
      - api
  redis:
    container_name: cache-database
    image: redis
    command: redis-server --appendonly yes --requirepass 6TmMrPc_h2ST3UpxQ
    ports:
      - "6379:6379"
volumes:
  db-data:
  emqx-data:
  emqx-etc:
  emqx-log:
  mongodb:
networks:
  api:
