version: "3.1"

services:
  api:
    build: .
    restart: unless-stopped
    command: npm start
    ports:
      - 3000:3000
      - 65080:65080
    volumes:
      - .:/usr/app
      - /usr/app/node_modules/
      - /home/postesolar/conf/web:/usr/app/conf
    networks:
      - api
  # database:
  #   container_name: postgres-teste
  #   image: postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_PASSWORD: 1212
  #     POSTGRES_USER: postesolar
  #   ports:
  #     - 5435:5432
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
# volumes:
#   db-data:
networks:
  api:
